Sixscape profile addition
pkic/pkic.github.io pull request #10
Opened 2021-07-14 11:00 UTC by ramsixscape

Updated our Initial profile details

Regards,
Ram Kishore

2021-07-14 11:55 UTC, vanbroup requested changes
The logo file `assets/images/members/sixscape/sixscape.svg` is a PNG embedded in SVG and not a real SVG file. 

```svg
<svg width="2666" height="1066" viewBox="0 0 2666 1066" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<path d="M2666 0H0V1066H2666V0Z" fill="url(#pattern0)"/>
<defs>
<pattern id="pattern0" patternContentUnits="objectBoundingBox" width="1" height="1">
<use xlink:href="#image0" transform="scale(0.000375094 0.000938086)"/>
</pattern>
<image id="image0" width="2666" height="1066" xlink:href="data:image/png;base64 iVBORw0KGgoAAAANSUhEUgAACmoAAAQqCAYAAABNmbJsAAAgAElEQVR4AezdeZCc533Y............"/>
</defs>
</svg>

```
Can you provide a vectorized SVG version of the logo?
We can convert an AI or other vector-based file if needed.

2021-07-14 11:55 UTC, vanbroup commented on data/members/sixscape.yaml
> +memberSince: 2021-07-14
This would be `2021-07-20`, assuming approved.

2021-07-14 11:55 UTC, vanbroup commented on data/members/sixscape.yaml
> +  feed:
It would be good to include a feed as this would be included on your profile and in the aggregate news for the whole site, I found one here `https://sixscape.com/feed/` but that seems to list 'dummy' news...

2021-07-14 11:55 UTC, vanbroup commented on data/members/sixscape.yaml
> +  twitter: https://twitter.com/sixscape_comm?lang=en
Remove optional parameters
```suggestion
  twitter: https://twitter.com/sixscape_comm
```

2021-07-14 11:55 UTC, vanbroup commented on data/members/sixscape.yaml
> +  linkedin: https://www.linkedin.com/company/sixscape-communications-global/?originalSubdomain=sg
Remove optional parameters
```suggestion
  linkedin: https://www.linkedin.com/company/sixscape-communications-global/
```

2021-07-14 11:55 UTC, vanbroup commented on data/members/sixscape.yaml
> +representatives:
It would be nice if you could include profile photos of the representatives.

2021-07-16 03:07 UTC, ramsixscape commented
> The logo file `assets/images/members/sixscape/sixscape.svg` is a PNG embedded in SVG and not a real SVG file.
> 
> ```
> <svg width="2666" height="1066" viewBox="0 0 2666 1066" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
> <path d="M2666 0H0V1066H2666V0Z" fill="url(#pattern0)"/>
> <defs>
> <pattern id="pattern0" patternContentUnits="objectBoundingBox" width="1" height="1">
> <use xlink:href="#image0" transform="scale(0.000375094 0.000938086)"/>
> </pattern>
> <image id="image0" width="2666" height="1066" xlink:href="data:image/png;base64 iVBORw0KGgoAAAANSUhEUgAACmoAAAQqCAYAAABNmbJsAAAgAElEQVR4AezdeZCc533Y............"/>
> </defs>
> </svg>
> ```
> 
> Can you provide a vectorized SVG version of the logo?
> We can convert an AI or other vector-based file if needed.

Updated the image

2021-07-16 03:07 UTC, ramsixscape commented on data/members/sixscape.yaml
> +memberSince: 2021-07-14
Updated

2021-07-16 03:08 UTC, ramsixscape commented on data/members/sixscape.yaml
> +  feed:
Included the feed link. The dummy URLs are resolved. However please ignore the references in the Guid.

2021-07-16 03:09 UTC, ramsixscape commented on data/members/sixscape.yaml
> +representatives:
Would that be ok, if we give a separate PR with the images?

2021-07-16 06:51 UTC, vanbroup commented
The representative profile photos can also be provided in a sperate merge request when this one is merged. 

I corrected some items in the SVG logo as some of the effects got lost in the version you uploaded, also the name was not vectorized which caused it to be shown in the system font.

The current profile looks like this:

![image](https://user-images.githubusercontent.com/722070/125904530-2e1f0227-a945-4139-81e5-0b3f49ba65bf.png)

2021-07-16 06:52 UTC, vanbroup approved these changes

2021-07-20 09:24 UTC, merged