Update TRUSTZONE profile
pkic/pkic.github.io pull request #2
Opened 2021-04-26 08:30 UTC by ChristianBrandenburg

Hi Paul 

We would like to update our profile with the following content and pictures. 

Kind regards
Christian Brandenburg
Sales Engineer @ TRUSTZONE

2021-04-26 09:07 UTC, vanbroup requested changes
With the mentioned changes the profile would look like:

![image](https://user-images.githubusercontent.com/722070/116056503-2910f780-a67e-11eb-86b2-bd4a252b125a.png)

Can you crop the profile photos to be more like a square, this would give all images an equal with, like other profiles?

To locally preview the site, install/download the [hugo command](https://gohugo.io/getting-started/installing/) and run `hugo server -D` in the root of the repository.

You can also include a video about TRUSTZONE in the profile body if you like, include the following snippet in the `trustzone.md` file and change to code to the video id you would like to include.

`{{< youtube jdpiTcc9d4U >}}`

2021-04-26 13:19 UTC, ChristianBrandenburg commented on data/members/trustzone.yaml
> +      Jacob is the CEO and Co-founder of TRUSTZONE and represents the organization at the PKI Consortium.
Yup, I'll ask Jacob to add some more backstory

2021-04-26 13:20 UTC, ChristianBrandenburg commented on data/members/trustzone.yaml
> +    description:
Yup, I'll ask Svein to add some more backstory

2021-04-26 13:20 UTC, ChristianBrandenburg commented on data/members/trustzone.yaml
>    - id: jhnielsen
Thank you for the explanation. I will rename the photo.

2021-04-29 15:14 UTC, ChristianBrandenburg commented on data/members/trustzone.yaml
> +      Jacob is the CEO and Co-founder of TRUSTZONE and represents the organization at the PKI Consortium.
I have updated Jacobs background section

2021-04-29 15:14 UTC, ChristianBrandenburg commented on data/members/trustzone.yaml
> +    description:
I have updated Sveins background section

2021-04-29 15:16 UTC, ChristianBrandenburg commented on data/members/trustzone.yaml
> +  feed:
We have decided to to keep the blog posts in after all

2021-05-04 12:52 UTC, vanbroup approved these changes

2021-05-04 12:52 UTC, merged